import 'package:audioplayers/audioplayers.dart';
import 'package:flutter/foundation.dart';

import '../constants/music_constants.dart';

/// The note itself, played on a correct answer.
///
/// An ear-training app with a silent right/wrong was teaching the eye and not
/// the ear. The haptic says "yes"; this says *which note that was* — so every
/// correct tap is also one more hearing of the ♭3 of A, which is the thing
/// actually being learned.
///
/// Twelve short tones, C4 to B4, generated by tool/gen_tones.dart. Wrong
/// answers stay silent on purpose: the sound is a reward and a lesson, and
/// playing the right note after a wrong tap would teach the wrong pairing.
class NoteSound {
  NoteSound._();
  static final NoteSound instance = NoteSound._();

  static const _names = ['C', 'Cs', 'D', 'Ds', 'E', 'F', 'Fs', 'G', 'Gs', 'A', 'As', 'B'];

  // Two players, alternated: a fast run of correct answers can start a new
  // tone before the previous one has released, and one player would cut it.
  final _players = [
    AudioPlayer(playerId: 'note_tone_a'),
    AudioPlayer(playerId: 'note_tone_b'),
  ];
  var _next = 0;
  bool _ready = false;

  Future<void> _prepare() async {
    if (_ready) return;
    _ready = true;
    for (final p in _players) {
      try {
        await p.setReleaseMode(ReleaseMode.stop);
        await p.setPlayerMode(PlayerMode.lowLatency);
      } catch (_) {
        // Low-latency mode is a hint; a platform that refuses it still plays.
      }
    }
  }

  /// Plays the pitch class of [note] — any spelling the app uses, slash forms
  /// included. Never throws: a sound that fails is a sound that did not play.
  Future<void> play(String note) async {
    if (kIsWeb) return; // the web preview has no audio session to speak of
    final semi = kNoteToSemitone[note.split('/').first.trim()];
    if (semi == null) return;
    try {
      await _prepare();
      final p = _players[_next];
      _next = (_next + 1) % _players.length;
      await p.stop();
      await p.play(AssetSource('audio/tones/${_names[semi % 12]}.wav'));
    } catch (e) {
      if (kDebugMode) debugPrint('[NoteSound] $e');
    }
  }
}
